name: data DVC save

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  dvc_save:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
       pip install -r requirements.txt
       pip install dvc
       pip install dvc-s3

    - name: Set Git identity
      run: |
        git config --global user.email 'zan.povse11@gmail.com'
        git config --global user.name 'ZanPovseGit'

    - name: Run Python Script
      run: python src/data/requestGit.py

    - name: Add Data to DVC
      run: | 
        dvc add data/tempdata/processed/*.json
      working-directory: ${{ github.workspace }} 

    - name: Configure DVC Remote
      run: |
        dvc remote add ppu s3://dvc -f
        dvc remote modify ppu endpointurl https://dagshub.com/ZanPovseGit/inteligentniSistem.s3
        dvc remote modify ppu --local access_key_id bdf091cc3f58df2c8346bb8ce616545e0e40b351
        dvc remote modify ppu --local secret_access_key bdf091cc3f58df2c8346bb8ce616545e0e40b351
        dvc pull -r ppu
        dvc push -r ppu
      env:
        DVC_REPOSITORY: ./  

    - name: Commit and Push to GitHub
      run: |
        git config --global user.name 'ZanPovseGit'
        git config --global user.email 'zan.povse11@gmail.com'        
        git add .
        git commit -am "Update DVC data"
        git push
