name: Run Python Script and Save Data to DVC

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run_python_and_save_data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
       pip install -r requirements.txt
       pip install dvc
       pip install dvc-s3

    - name: Run Python Script
      run: python requestGit.py

    - name: Add Data to DVC
      run: | 
        dvc add data/tempdata/processed/*
        git add data/tempdata/processed/*.dvc
        git commit -m "Add generated data to DVC"
      working-directory: ${{ github.workspace }} 

    - name: Configure DVC Remote
      run: |
        dvc remote add origin https://dagshub.com/ZanPovseGit/inteligentniSistem.s3
        dvc pull  
        dvc push  
      env:
        DVC_REPOSITORY: ./  

    - name: Commit and Push to GitHub
      run: |
        git config --local user.email 'zan.povse11@gmail.com'
        git config --local user.name 'ZanPovseGit'
        git add .
        git commit -m "Update DVC data"
        git push
