name: Data Download

on:
  push:
    branches:
      - master

jobs:
  check-api1:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check API 1
      run: |
        # Add commands to check if API 1 is running
        # For example:
        curl -sSf https://api.open-meteo.com/v1/forecast?latitude=52.52&longitude=13.41&daily=weather_code,temperature_2m_max,rain_sum || exit 1

  check-api2:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check API 2
      run: |
        # Add commands to check if API 2 is running
        # For example:
        curl -sSf https://api.jcdecaux.com/vls/v1/stations?contract=maribor&apiKey=5e150537116dbc1786ce5bec6975a8603286526b || exit 1

  download-data-script1:
    needs: check-api1
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt 
        
    - name: Run Python script
      run: python src/data/requestGit.py

  download-data-script2:
    needs: check-api2
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt 
        
    - name: Run Python script
      run: python src/data/weather.py

  download-data-script3:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt 
        
    - name: Run Python script
      run: python src/data/bike.py

  dvc-push:
    needs: [download-data-script1, download-data-script2, download-data-script3]
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Install DVC and dvc-s3
      run: |
        pip install dvc-s3
        pip install pyopenssl==24.0.0
      
    - name: Push data to DVC remote
      run: |
        dvc push -r origin
        dvc remote modify origin --local access_key_id bdf091cc3f58df2c8346bb8ce616545e0e40b351
        dvc remote modify origin --local secret_access_key bdf091cc3f58df2c8346bb8ce616545e0e40b351

